/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import key.KeyType;
import person.Person;

/**
 *
 * @author Windows
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    private Person Lily;
    private Person Bob;
    private Person Jary;
    private boolean cheat = false;

    public View() throws NoSuchAlgorithmException {
        initComponents();
        Lily = new Person();
        Bob = new Person();
        Jary = new Person();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().removeAll();
        getContentPane().add(ContentPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new javax.swing.JPanel();
        MaHoaDuLieu = new javax.swing.JPanel();
        Lily_avt = new javax.swing.JLabel();
        Bob_avt = new javax.swing.JLabel();
        Jary_avt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBob = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLily = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtJary = new javax.swing.JTextArea();
        btnLiLy_Bob = new javax.swing.JButton();
        btnLiLyJary = new javax.swing.JButton();
        btnJaryLiLy = new javax.swing.JButton();
        btnJaryBob = new javax.swing.JButton();
        btnBobLiLy = new javax.swing.JButton();
        btnBobJary = new javax.swing.JButton();
        lilyReceive = new javax.swing.JLabel();
        bobReceive = new javax.swing.JLabel();
        JaryReceive = new javax.swing.JLabel();
        MaHoa = new javax.swing.JButton();
        ChuKySo = new javax.swing.JButton();
        modeRSA = new javax.swing.JButton();
        modeSHA256 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TaoChuKySo = new javax.swing.JPanel();
        Lily_avt1 = new javax.swing.JLabel();
        Bob_avt1 = new javax.swing.JLabel();
        Jary_avt1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBob1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtLily1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtJary1 = new javax.swing.JTextArea();
        btnLiLy_Bob1 = new javax.swing.JButton();
        btnJaryLiLy1 = new javax.swing.JButton();
        btnBobLiLy1 = new javax.swing.JButton();
        lilyReceive1 = new javax.swing.JLabel();
        bobReceive1 = new javax.swing.JLabel();
        JaryReceive1 = new javax.swing.JLabel();
        MaHoa1 = new javax.swing.JButton();
        ChuKySo1 = new javax.swing.JButton();
        LiLyCheckValid = new javax.swing.JLabel();
        JaryCheckValid = new javax.swing.JLabel();
        BobCheckValid = new javax.swing.JLabel();
        lilyReceiveEncypt = new javax.swing.JLabel();
        lilyEncrypt = new javax.swing.JLabel();
        JaryReceiveEncrypt = new javax.swing.JLabel();
        JaryEncrypt = new javax.swing.JLabel();
        bobReceiveEncrypt = new javax.swing.JLabel();
        bobEncrypt = new javax.swing.JLabel();
        ChuKySo2 = new javax.swing.JButton();
        ChuKySo3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bobcheatbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        ContentPanel.setBackground(new java.awt.Color(33, 33, 33));

        MaHoaDuLieu.setBackground(new java.awt.Color(33, 33, 33));

        Lily_avt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lily_avt.setForeground(new java.awt.Color(255, 255, 255));
        Lily_avt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693201-removebg-preview.png"))); // NOI18N
        Lily_avt.setText("LILY");

        Bob_avt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bob_avt.setForeground(new java.awt.Color(255, 255, 255));
        Bob_avt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693218-removebg-preview.png"))); // NOI18N
        Bob_avt.setText("BOB");

        Jary_avt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jary_avt.setForeground(new java.awt.Color(255, 255, 255));
        Jary_avt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693230-removebg-preview.png"))); // NOI18N
        Jary_avt.setText("JARY");

        txtBob.setColumns(20);
        txtBob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBob.setRows(5);
        jScrollPane1.setViewportView(txtBob);

        txtLily.setColumns(20);
        txtLily.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLily.setRows(5);
        jScrollPane2.setViewportView(txtLily);

        txtJary.setColumns(20);
        txtJary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJary.setRows(5);
        jScrollPane3.setViewportView(txtJary);

        btnLiLy_Bob.setText("Gửi Tin Nhắn Cho Bob");
        btnLiLy_Bob.setPreferredSize(new java.awt.Dimension(75, 50));
        btnLiLy_Bob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiLy_BobActionPerformed(evt);
            }
        });

        btnLiLyJary.setText("Gửi Tin Nhắn Cho Jary");
        btnLiLyJary.setPreferredSize(new java.awt.Dimension(75, 50));
        btnLiLyJary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiLyJaryActionPerformed(evt);
            }
        });

        btnJaryLiLy.setText("Gửi Tin Nhắn Cho Lily");
        btnJaryLiLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJaryLiLyActionPerformed(evt);
            }
        });

        btnJaryBob.setText("Gửi Tin Nhắn Cho Bob");
        btnJaryBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJaryBobActionPerformed(evt);
            }
        });

        btnBobLiLy.setText("Gửi Tin Nhắn Cho LiLy");
        btnBobLiLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBobLiLyActionPerformed(evt);
            }
        });

        btnBobJary.setText("Gửi Tin Nhắn Cho Jary");
        btnBobJary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBobJaryActionPerformed(evt);
            }
        });

        lilyReceive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lilyReceive.setForeground(new java.awt.Color(255, 255, 255));
        lilyReceive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lilyReceive.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "LiLy's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        lilyReceive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bobReceive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bobReceive.setForeground(new java.awt.Color(255, 255, 255));
        bobReceive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bobReceive.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Bob's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        bobReceive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JaryReceive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JaryReceive.setForeground(new java.awt.Color(255, 255, 255));
        JaryReceive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JaryReceive.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Jary's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JaryReceive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MaHoa.setBackground(new java.awt.Color(33, 33, 33));
        MaHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHoa.setForeground(new java.awt.Color(255, 255, 255));
        MaHoa.setText("MÃ HÓA (RSA)");
        MaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHoaActionPerformed(evt);
            }
        });

        ChuKySo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuKySo.setText("TẠO CHỮ KÝ SỐ (authentication)");
        ChuKySo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuKySoActionPerformed(evt);
            }
        });

        modeRSA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modeRSA.setText("Sử Dụng RSA");
        modeRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeRSAActionPerformed(evt);
            }
        });

        modeSHA256.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modeSHA256.setText("Sử Dụng SHA256");
        modeSHA256.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeSHA256ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaHoaDuLieuLayout = new javax.swing.GroupLayout(MaHoaDuLieu);
        MaHoaDuLieu.setLayout(MaHoaDuLieuLayout);
        MaHoaDuLieuLayout.setHorizontalGroup(
            MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addComponent(MaHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(ChuKySo, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addComponent(btnLiLy_Bob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLiLyJary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(Lily_avt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lilyReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bobReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                                .addComponent(Bob_avt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))))
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBobLiLy, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBobJary, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modeRSA)
                        .addGap(18, 18, 18)
                        .addComponent(modeSHA256, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addComponent(btnJaryLiLy, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJaryBob, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(Jary_avt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JaryReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        MaHoaDuLieuLayout.setVerticalGroup(
            MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChuKySo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeRSA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeSHA256, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(lilyReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaHoaDuLieuLayout.createSequentialGroup()
                                .addComponent(JaryReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lily_avt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jary_avt))
                        .addGap(16, 16, 16)
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(20, 20, 20)
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLiLy_Bob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLiLyJary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnJaryLiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnJaryBob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(MaHoaDuLieuLayout.createSequentialGroup()
                        .addComponent(Bob_avt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MaHoaDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBobLiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBobJary, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bobReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(163, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MaHoaDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MaHoaDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 33, 33));

        TaoChuKySo.setBackground(new java.awt.Color(33, 33, 33));

        Lily_avt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lily_avt1.setForeground(new java.awt.Color(255, 255, 255));
        Lily_avt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693201-removebg-preview.png"))); // NOI18N
        Lily_avt1.setText("LILY");

        Bob_avt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bob_avt1.setForeground(new java.awt.Color(255, 255, 255));
        Bob_avt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693218-removebg-preview.png"))); // NOI18N
        Bob_avt1.setText("BOB");

        Jary_avt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jary_avt1.setForeground(new java.awt.Color(255, 255, 255));
        Jary_avt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-sign-icon-person-symbol-human-avatar-vector-12693230-removebg-preview.png"))); // NOI18N
        Jary_avt1.setText("JARY");

        txtBob1.setColumns(20);
        txtBob1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBob1.setRows(5);
        jScrollPane4.setViewportView(txtBob1);

        txtLily1.setColumns(20);
        txtLily1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLily1.setRows(5);
        jScrollPane5.setViewportView(txtLily1);

        txtJary1.setColumns(20);
        txtJary1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJary1.setRows(5);
        jScrollPane6.setViewportView(txtJary1);

        btnLiLy_Bob1.setText("Gửi Đi Tin Nhắn");
        btnLiLy_Bob1.setPreferredSize(new java.awt.Dimension(75, 50));
        btnLiLy_Bob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiLy_Bob1ActionPerformed(evt);
            }
        });

        btnJaryLiLy1.setText("Gửi Đi Tin Nhắn");
        btnJaryLiLy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJaryLiLy1ActionPerformed(evt);
            }
        });

        btnBobLiLy1.setText("Gửi Đi Tin Nhắn");
        btnBobLiLy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBobLiLy1ActionPerformed(evt);
            }
        });

        lilyReceive1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lilyReceive1.setForeground(new java.awt.Color(255, 255, 255));
        lilyReceive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lilyReceive1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "LiLy's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        lilyReceive1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bobReceive1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bobReceive1.setForeground(new java.awt.Color(255, 255, 255));
        bobReceive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bobReceive1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Bob's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        bobReceive1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JaryReceive1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JaryReceive1.setForeground(new java.awt.Color(255, 255, 255));
        JaryReceive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JaryReceive1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Jary's ReceiveMessage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JaryReceive1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MaHoa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHoa1.setText("MÃ HÓA (RSA)");
        MaHoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHoa1ActionPerformed(evt);
            }
        });

        ChuKySo1.setBackground(new java.awt.Color(33, 33, 33));
        ChuKySo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuKySo1.setForeground(new java.awt.Color(255, 255, 255));
        ChuKySo1.setText("TẠO CHỮ KÝ SỐ (authentication)");
        ChuKySo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuKySo1ActionPerformed(evt);
            }
        });

        LiLyCheckValid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        LiLyCheckValid.setForeground(new java.awt.Color(255, 255, 255));
        LiLyCheckValid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiLyCheckValid.setIconTextGap(10);

        JaryCheckValid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JaryCheckValid.setForeground(new java.awt.Color(255, 255, 255));
        JaryCheckValid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JaryCheckValid.setIconTextGap(10);

        BobCheckValid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BobCheckValid.setForeground(new java.awt.Color(255, 255, 255));
        BobCheckValid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BobCheckValid.setIconTextGap(10);

        lilyReceiveEncypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lilyReceiveEncypt.setForeground(new java.awt.Color(255, 255, 255));
        lilyReceiveEncypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lilyReceiveEncypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Mã Hash ban đầu được gửi đi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        lilyReceiveEncypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lilyEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lilyEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        lilyEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lilyEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "LiLy's Giải Mã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        lilyEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JaryReceiveEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JaryReceiveEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        JaryReceiveEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JaryReceiveEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Mã Hash ban đầu được gửi đi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JaryReceiveEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JaryEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JaryEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        JaryEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JaryEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Jary's Giải Mã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JaryEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bobReceiveEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bobReceiveEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        bobReceiveEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bobReceiveEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Mã Hash ban đầu được gửi đi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        bobReceiveEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bobEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bobEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        bobEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bobEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Bob's Giải Mã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        bobEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ChuKySo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuKySo2.setText("SỬ DỤNG RSA");
        ChuKySo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuKySo2ActionPerformed(evt);
            }
        });

        ChuKySo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuKySo3.setText("SỬ DỤNG SHA-256");
        ChuKySo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuKySo3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bob's Cheat :");

        bobcheatbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Không" ,"Đổi Tin Nhắn của Jary (Không Có Khóa)","Đổi Tin Nhắn của Jary (Có Khóa)"}));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHEAT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaoChuKySoLayout = new javax.swing.GroupLayout(TaoChuKySo);
        TaoChuKySo.setLayout(TaoChuKySoLayout);
        TaoChuKySoLayout.setHorizontalGroup(
            TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                                .addComponent(Lily_avt1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LiLyCheckValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)
                            .addComponent(lilyReceive1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLiLy_Bob1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(lilyEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoChuKySoLayout.createSequentialGroup()
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                                .addComponent(MaHoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChuKySo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lilyReceiveEncypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bobReceive1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBobLiLy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(bobReceiveEncrypt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bobEncrypt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(Bob_avt1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BobCheckValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bobcheatbox, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChuKySo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChuKySo3))
                    .addComponent(jScrollPane6)
                    .addComponent(JaryReceive1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJaryLiLy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(Jary_avt1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JaryCheckValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JaryReceiveEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JaryEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        TaoChuKySoLayout.setVerticalGroup(
            TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoChuKySoLayout.createSequentialGroup()
                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                                .addComponent(lilyReceiveEncypt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(lilyEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lilyReceive1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                                .addComponent(JaryReceiveEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JaryEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JaryReceive1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lily_avt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jary_avt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LiLyCheckValid, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JaryCheckValid, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TaoChuKySoLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChuKySo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaHoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoChuKySoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bobcheatbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ChuKySo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ChuKySo3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(46, 46, 46)
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bob_avt1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BobCheckValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBobLiLy1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bobReceive1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addComponent(bobReceiveEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bobEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TaoChuKySoLayout.createSequentialGroup()
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))
                        .addGap(20, 20, 20)
                        .addGroup(TaoChuKySoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLiLy_Bob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJaryLiLy1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TaoChuKySo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TaoChuKySo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiLyJaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiLyJaryActionPerformed
        // TODO add your handling code here:
        String message = txtLily.getText().trim();
        Lily.setMessage(Lily.stringToBigInteger(message));
        BigInteger enryptMes = Lily.getKey().encryptRSA(Lily.getMessage(), Jary.getKey().getE(), Jary.getKey().getN());
        bobReceive.setText(Bob.BigIntegerToString(Bob.getKey().decryptRSA(enryptMes, Bob.getKey().getD(), Bob.getKey().getN())));
        JaryReceive.setText(Jary.BigIntegerToString(Jary.getKey().decryptRSA(enryptMes, Jary.getKey().getD(), Jary.getKey().getN())));
    }//GEN-LAST:event_btnLiLyJaryActionPerformed

    private void btnLiLy_BobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiLy_BobActionPerformed
        // TODO add your handling code here:
        String message = txtLily.getText().trim();
        Lily.setMessage(Lily.stringToBigInteger(message));
        BigInteger enryptMes = Lily.getKey().encryptRSA(Lily.getMessage(), Bob.getKey().getE(), Bob.getKey().getN());
        bobReceive.setText(Bob.BigIntegerToString(Bob.getKey().decryptRSA(enryptMes, Bob.getKey().getD(), Bob.getKey().getN())));
        JaryReceive.setText(Jary.BigIntegerToString(Jary.getKey().decryptRSA(enryptMes, Jary.getKey().getD(), Jary.getKey().getN())));
    }//GEN-LAST:event_btnLiLy_BobActionPerformed

    private void btnBobLiLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBobLiLyActionPerformed
        // TODO add your handling code here:
        String message = txtBob.getText().trim();
        Bob.setMessage(Bob.stringToBigInteger(message));
        BigInteger enryptMes = Bob.getKey().encryptRSA(Bob.getMessage(), Lily.getKey().getE(), Lily.getKey().getN());
        lilyReceive.setText(Lily.BigIntegerToString(Lily.getKey().decryptRSA(enryptMes, Lily.getKey().getD(), Lily.getKey().getN())));
        JaryReceive.setText(Jary.BigIntegerToString(Jary.getKey().decryptRSA(enryptMes, Jary.getKey().getD(), Jary.getKey().getN())));
    }//GEN-LAST:event_btnBobLiLyActionPerformed

    private void btnBobJaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBobJaryActionPerformed
        // TODO add your handling code here:
        String message = txtBob.getText().trim();
        Bob.setMessage(Bob.stringToBigInteger(message));
        BigInteger enryptMes = Bob.getKey().encryptRSA(Bob.getMessage(), Jary.getKey().getE(), Jary.getKey().getN());
        lilyReceive.setText(Lily.BigIntegerToString(Lily.getKey().decryptRSA(enryptMes, Lily.getKey().getD(), Lily.getKey().getN())));
        JaryReceive.setText(Jary.BigIntegerToString(Jary.getKey().decryptRSA(enryptMes, Jary.getKey().getD(), Jary.getKey().getN())));
    }//GEN-LAST:event_btnBobJaryActionPerformed

    private void btnJaryLiLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJaryLiLyActionPerformed
        // TODO add your handling code here:
        String message = txtJary.getText().trim();
        Jary.setMessage(Jary.stringToBigInteger(message));
        BigInteger enryptMes = Jary.getKey().encryptRSA(Jary.getMessage(), Lily.getKey().getE(), Lily.getKey().getN());
        lilyReceive.setText(Lily.BigIntegerToString(Lily.getKey().decryptRSA(enryptMes, Lily.getKey().getD(), Lily.getKey().getN())));
        bobReceive.setText(Jary.BigIntegerToString(Jary.getKey().decryptRSA(enryptMes, Jary.getKey().getD(), Jary.getKey().getN())));
    }//GEN-LAST:event_btnJaryLiLyActionPerformed

    private void btnJaryBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJaryBobActionPerformed
        // TODO add your handling code here:
        String message = txtJary.getText().trim();
        Jary.setMessage(Jary.stringToBigInteger(message));
        BigInteger enryptMes = Jary.getKey().encryptRSA(Jary.getMessage(), Bob.getKey().getE(), Bob.getKey().getN());
        lilyReceive.setText(Lily.BigIntegerToString(Lily.getKey().decryptRSA(enryptMes, Lily.getKey().getD(), Lily.getKey().getN())));
        bobReceive.setText(Bob.BigIntegerToString(Bob.getKey().decryptRSA(enryptMes, Bob.getKey().getD(), Bob.getKey().getN())));
    }//GEN-LAST:event_btnJaryBobActionPerformed

    private void MaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHoaActionPerformed
        // TODO add your handling code here:
        getContentPane().removeAll();
        getContentPane().add(ContentPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_MaHoaActionPerformed

    private void ChuKySoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuKySoActionPerformed
        // TODO add your handling code here:
        getContentPane().removeAll();
        getContentPane().add(TaoChuKySo, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_ChuKySoActionPerformed

    private void btnLiLy_Bob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiLy_Bob1ActionPerformed
        // TODO add your handling code here:
        String message = txtLily1.getText().trim();
        Lily.setMessage(Lily.stringToBigInteger(message));
        BigInteger encryptMess = Lily.getKey().encryptSign(Lily.getMessage(), Lily.getKey().getD(), Lily.getKey().getN());
        Receive_Data(BobCheckValid, encryptMess, Lily, Bob, bobReceive1, bobReceiveEncrypt, bobEncrypt);
        Receive_Data(JaryCheckValid, encryptMess, Lily, Jary, JaryReceive1, JaryReceiveEncrypt, JaryEncrypt);
    }//GEN-LAST:event_btnLiLy_Bob1ActionPerformed
    public void Receive_Data(JLabel valid, BigInteger message, Person sender, Person receiver, JLabel receiveMess, JLabel receiveEncrypt, JLabel Decrypt) {
        BigInteger bob_Decrypt = receiver.getKey().decryptSign(message, sender.getKey().getE(), sender.getKey().getN());
        Decrypt.setText(bob_Decrypt.toString());
        receiveEncrypt.setText(sender.getMessage().toString());
        receiveMess.setText(receiver.BigIntegerToString(bob_Decrypt));
        
        if (Decrypt.getText().equals(receiveEncrypt.getText())) {
            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tick.png")));
            valid.setText("Không bị thay đổi");
        } else {
            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cross.png")));
            valid.setText("Bị thay đổi");
        }
        if(cheat){
            txtBob1.setText(receiver.BigIntegerToString(bob_Decrypt));
            cheat = false;
        }
    }
    private void btnJaryLiLy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJaryLiLy1ActionPerformed
        // TODO add your handling code here:
        if (bobcheatbox.getSelectedItem().toString().equals("Không")) {
            String message = txtJary1.getText().trim();
            Jary.setMessage(Jary.stringToBigInteger(message));
            BigInteger encryptMess = Jary.getKey().encryptSign(Jary.getMessage(), Jary.getKey().getD(), Jary.getKey().getN());
            Receive_Data(BobCheckValid, encryptMess, Jary, Bob, bobReceive1, bobReceiveEncrypt, bobEncrypt);
            Receive_Data(LiLyCheckValid, encryptMess, Jary, Lily, lilyReceive1, lilyReceiveEncypt, lilyEncrypt);
        } else {
            cheat = true;
            String message = txtJary1.getText().trim();
            Jary.setMessage(Jary.stringToBigInteger(message));
            BigInteger encryptMess = Jary.getKey().encryptSign(Jary.getMessage(), Jary.getKey().getD(), Jary.getKey().getN());
            Receive_Data(BobCheckValid, encryptMess, Jary, Bob, bobReceive1, bobReceiveEncrypt, bobEncrypt);
        }
    }//GEN-LAST:event_btnJaryLiLy1ActionPerformed

    private void btnBobLiLy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBobLiLy1ActionPerformed
        // TODO add your handling code here:
        String message = txtBob1.getText().trim();
        Bob.setMessage(Bob.stringToBigInteger(message));
        BigInteger encryptMess = Bob.getKey().encryptSign(Bob.getMessage(), Bob.getKey().getD(), Bob.getKey().getN());
        Receive_Data(LiLyCheckValid, encryptMess, Bob, Lily, lilyReceive1, lilyReceiveEncypt, lilyEncrypt);
        Receive_Data(JaryCheckValid, encryptMess, Bob, Jary, JaryReceive1, JaryReceiveEncrypt, JaryEncrypt);
    }//GEN-LAST:event_btnBobLiLy1ActionPerformed

    private void MaHoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHoa1ActionPerformed
        // TODO add your handling code here:
        getContentPane().removeAll();
        getContentPane().add(ContentPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_MaHoa1ActionPerformed

    private void ChuKySo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuKySo1ActionPerformed
        // TODO add your handling code here:
        getContentPane().removeAll();
        getContentPane().add(TaoChuKySo, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_ChuKySo1ActionPerformed

    private void modeRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeRSAActionPerformed
        // TODO add your handling code here:
        KeyType k1 = new KeyType();
        k1.CreateKeyRSA(256);
        Lily.setKey(k1);
        KeyType k2 = new KeyType();
        k2.CreateKeyRSA(256);
        Bob.setKey(k2);
        KeyType k3 = new KeyType();
        k3.CreateKeyRSA(256);
        Jary.setKey(k3);
    }//GEN-LAST:event_modeRSAActionPerformed

    private void modeSHA256ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeSHA256ActionPerformed
        // TODO add your handling code here:
        KeyType k1 = new KeyType();
        try {
            k1.createKeySHA256(256);
            Lily.setKey(k1);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        KeyType k2 = new KeyType();
        try {
            k2.createKeySHA256(256);
            Bob.setKey(k2);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        KeyType k3 = new KeyType();
        try {
            k3.createKeySHA256(256);
            Jary.setKey(k3);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modeSHA256ActionPerformed

    private void ChuKySo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuKySo2ActionPerformed
        // TODO add your handling code here:
        KeyType k1 = new KeyType();
        k1.CreateKeyRSA(256);
        Lily.setKey(k1);
        KeyType k2 = new KeyType();
        k2.CreateKeyRSA(256);
        Bob.setKey(k2);
        KeyType k3 = new KeyType();
        k3.CreateKeyRSA(256);
        Jary.setKey(k3);
    }//GEN-LAST:event_ChuKySo2ActionPerformed

    private void ChuKySo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuKySo3ActionPerformed
        // TODO add your handling code here:
        KeyType k1 = new KeyType();
        try {
            k1.createKeySHA256(256);
            Lily.setKey(k1);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        KeyType k2 = new KeyType();
        try {
            k2.createKeySHA256(256);
            Bob.setKey(k2);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        KeyType k3 = new KeyType();
        try {
            k3.createKeySHA256(256);
            Jary.setKey(k3);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChuKySo3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!bobcheatbox.getSelectedItem().toString().equals("Không")) {
            String message = txtBob1.getText().trim();
            Bob.setMessage(Bob.stringToBigInteger(message));
            BigInteger encryptMess;
            if(bobcheatbox.getSelectedItem().toString().equals("Đổi Tin Nhắn của Jary (Có Khóa)")){
                encryptMess = Bob.getKey().encryptSign(Bob.getMessage(), Jary.getKey().getD(), Jary.getKey().getN());
            }
            else{
                encryptMess = Bob.getKey().encryptSign(Bob.getMessage(), Bob.getKey().getD(), Bob.getKey().getN());
            }
            Receive_Data(LiLyCheckValid, encryptMess, Jary, Lily, lilyReceive1, lilyReceiveEncypt, lilyEncrypt);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResetText();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ResetText();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new View().setVisible(true);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void ResetText(){
        txtJary.setText("");
        txtBob.setText("");
        txtLily.setText("");
        txtJary1.setText("");
        txtBob1.setText("");
        txtLily1.setText("");
        lilyEncrypt.setText("");
        LiLyCheckValid.setText("");
        lilyReceive1.setText("");
        lilyReceive.setText("");
        bobEncrypt.setText("");
        BobCheckValid.setText("");
        bobReceive1.setText("");
        bobReceive.setText("");
        JaryCheckValid.setText("");
        JaryCheckValid.setText("");
        JaryReceive1.setText("");
        JaryReceive.setText("");
        JaryReceiveEncrypt.setText("");
        JaryEncrypt.setText("");
        bobReceiveEncrypt.setText("");
        bobEncrypt.setText("");
        lilyReceiveEncypt.setText("");
        lilyEncrypt.setText("");
        JaryCheckValid.setIcon(null);
        BobCheckValid.setIcon(null);
        LiLyCheckValid.setIcon(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BobCheckValid;
    private javax.swing.JLabel Bob_avt;
    private javax.swing.JLabel Bob_avt1;
    private javax.swing.JButton ChuKySo;
    private javax.swing.JButton ChuKySo1;
    private javax.swing.JButton ChuKySo2;
    private javax.swing.JButton ChuKySo3;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JLabel JaryCheckValid;
    private javax.swing.JLabel JaryEncrypt;
    private javax.swing.JLabel JaryReceive;
    private javax.swing.JLabel JaryReceive1;
    private javax.swing.JLabel JaryReceiveEncrypt;
    private javax.swing.JLabel Jary_avt;
    private javax.swing.JLabel Jary_avt1;
    private javax.swing.JLabel LiLyCheckValid;
    private javax.swing.JLabel Lily_avt;
    private javax.swing.JLabel Lily_avt1;
    private javax.swing.JButton MaHoa;
    private javax.swing.JButton MaHoa1;
    private javax.swing.JPanel MaHoaDuLieu;
    private javax.swing.JPanel TaoChuKySo;
    private javax.swing.JLabel bobEncrypt;
    private javax.swing.JLabel bobReceive;
    private javax.swing.JLabel bobReceive1;
    private javax.swing.JLabel bobReceiveEncrypt;
    private javax.swing.JComboBox<String> bobcheatbox;
    private javax.swing.JButton btnBobJary;
    private javax.swing.JButton btnBobLiLy;
    private javax.swing.JButton btnBobLiLy1;
    private javax.swing.JButton btnJaryBob;
    private javax.swing.JButton btnJaryLiLy;
    private javax.swing.JButton btnJaryLiLy1;
    private javax.swing.JButton btnLiLyJary;
    private javax.swing.JButton btnLiLy_Bob;
    private javax.swing.JButton btnLiLy_Bob1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lilyEncrypt;
    private javax.swing.JLabel lilyReceive;
    private javax.swing.JLabel lilyReceive1;
    private javax.swing.JLabel lilyReceiveEncypt;
    private javax.swing.JButton modeRSA;
    private javax.swing.JButton modeSHA256;
    private javax.swing.JTextArea txtBob;
    private javax.swing.JTextArea txtBob1;
    private javax.swing.JTextArea txtJary;
    private javax.swing.JTextArea txtJary1;
    private javax.swing.JTextArea txtLily;
    private javax.swing.JTextArea txtLily1;
    // End of variables declaration//GEN-END:variables
}
